//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS_PRE {
    using System;
    using System.ComponentModel;
    using CrystalDecisions.Shared;
    using CrystalDecisions.ReportSource;
    using CrystalDecisions.CrystalReports.Engine;
    
    
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
    public class ads010_R01 : ReportClass {
        
        public ads010_R01() {
========
    public class ads007_R01b : ReportClass {
        
        public ads007_R01b() {
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
        }
        
        public override string ResourceName {
            get {
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
                return "ads010_R01.rpt";
========
                return "ads007_R01b.rpt";
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
            }
            set {
                // Do nothing
            }
        }
        
        public override bool NewGenerator {
            get {
                return true;
            }
            set {
                // Do nothing
            }
        }
        
        public override string FullResourceName {
            get {
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
                return "CRS_PRE.ADS.ads010_R01.rpt";
========
                return "CRS_PRE.ADS.ads007_R01b.rpt";
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
            }
            set {
                // Do nothing
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section1 {
            get {
                return this.ReportDefinition.Sections[0];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section2 {
            get {
                return this.ReportDefinition.Sections[1];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section3 {
            get {
                return this.ReportDefinition.Sections[2];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section4 {
            get {
                return this.ReportDefinition.Sections[3];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section5 {
            get {
                return this.ReportDefinition.Sections[4];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.Shared.IParameterField Parameter_vc_ide_usr {
            get {
                return this.DataDefinition.ParameterFields[0];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.Shared.IParameterField Parameter_vc_nom_emp {
            get {
                return this.DataDefinition.ParameterFields[1];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.Shared.IParameterField Parameter_vc_est_ado {
            get {
                return this.DataDefinition.ParameterFields[2];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
        public CrystalDecisions.Shared.IParameterField Parameter_vc_ord_dat {
========
        public CrystalDecisions.Shared.IParameterField Parameter_ag_est_ado {
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
            get {
                return this.DataDefinition.ParameterFields[3];
            }
        }
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.Shared.IParameterField Parameter_ar_est_ado {
            get {
                return this.DataDefinition.ParameterFields[4];
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.Shared.IParameterField Parameter_ar_ord_dat {
            get {
                return this.DataDefinition.ParameterFields[5];
            }
        }
    }
    
    [System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
    public class Cachedads010_R01 : Component, ICachedReport {
        
        public Cachedads010_R01() {
========
    }
    
    [System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
    public class Cachedads007_R01b : Component, ICachedReport {
        
        public Cachedads007_R01b() {
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public virtual bool IsCacheable {
            get {
                return true;
            }
            set {
                // 
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public virtual bool ShareDBLogonInfo {
            get {
                return false;
            }
            set {
                // 
            }
        }
        
        [Browsable(false)]
        [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public virtual System.TimeSpan CacheTimeOut {
            get {
                return CachedReportConstants.DEFAULT_TIMEOUT;
            }
            set {
                // 
            }
        }
        
        public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CreateReport() {
<<<<<<<< HEAD:CRS_PRE/ADS/ads010_R01.cs
            ads010_R01 rpt = new ads010_R01();
========
            ads007_R01b rpt = new ads007_R01b();
>>>>>>>> parent of 9316bd1 (CAMBIOS Y ACTUALIZACION DEL MODULO DE SEGURIDAD + REPORTES):CRS_PRE/ADS/ads007_R01b.cs
            rpt.Site = this.Site;
            return rpt;
        }
        
        public virtual string GetCustomizedCacheKey(RequestContext request) {
            String key = null;
            // // The following is the code used to generate the default
            // // cache key for caching report jobs in the ASP.NET Cache.
            // // Feel free to modify this code to suit your needs.
            // // Returning key == null causes the default cache key to
            // // be generated.
            // 
            // key = RequestContext.BuildCompleteCacheKey(
            //     request,
            //     null,       // sReportFilename
            //     this.GetType(),
            //     this.ShareDBLogonInfo );
            return key;
        }
    }
}
